#
# <( 'v' )> Work in Progress <( 'v' )>
#

application: dev
version: 1
runtime: python27
api_version: 1
threadsafe: true



handlers:
- url: /static/css
  static_dir: static/css
- url: /static/images
  static_dir: static/images
- url: /static/js
  static_dir: static/js

- url: /.*
  script: run.application



libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest